### ISSUE TITLE
user Journey+ Site Map : LP Website

### ISSUE THREAD

**Issue by minsiwang04** [Livepeer-Community-Node/Grant-Program#12]
**Problem**
 - Finding information on how to bond tokens as a first time user is a circuitous process
 - Bonding tokens are not as user friendly as it can be

**Objective**
 - Provide  updated user journey map for first time, nontechnical Livepeer  user to buy and bond the LPT on the livepeer site
 -  Provide site map and content suggestion as part of the website redesign 
 - Suggestions for metrics to track for the new site                                                                                               

**Assumptions**
 - User have metamask wallet installed
 - User persona for the user journey is the first time, nontechnical user who do not have LPT token 

**Milestones**

 - _Milestone #1:_Devise website architecture/flow, draft high-level content  for token holder pages, website page architecture  - May 22nd 
 - _Milestone #2:_ Formulate user  journey and site map for the new site (dependency on user research).   Identify necessary onboarding support (i.e. video, support article, coach marks, interactive, clickable tutorial), where the support would be (may not be on the website, but may be)     Due Date:  May 30th
 - _Milestone #3:_ Provide  metrics suggestions and suggestion for service to track site performance.  Due Date:  June 12th 
 - _Milestone #4:_ Provide hypothesis and test plan to be validated in future with A/B test .  Due Date:  June 21st

  

**Site Map+ User Journey Deliverable**

User Journey for the website will include: 
I. Persona:  Defined with user research with X. Yue.  . The user is a first time non technical LivePeer user who is interested in staking LPT token to a transcoder.  The user persona will be further break down by motivation to investment oriented user or utility/technology oriented user.  
II. User goal:  Define user goal for each step for website user from  sign up-> staking-> community member 
III. Process:  Map out the process for user to reach each step 

Sitemap: 
 + Site map for the updated website with key section and features 
+ Suggestions on support service 
+ High level content

**Other Deliverables**

 - Metrics review and benchmark for site performance 

 

Reference: 
![New user journey map_Initial](https://user-images.githubusercontent.com/8359700/56181788-65310c80-600f-11e9-9c4d-c7a5bfc8bf88.png)
Review of different user support services and customer journey for finding support  on the site

**Comment by RaffiSapire** [comment]
Hi @minsiwang04 this looks good! 
Because I'm planning the full site, we can set up a few hours over the coming weeks for M2. I will reach out via email. How many user journeys would you like to conduct? The reward is 5 LPT, and you can give me your discord name and I will connect you with Alvin to get those started. I'd love for him to start asking people if they want to join today. 

Also, can we get a bit more clear on what M2 entails? Ideally, I would like for this to identify what assets should exist and where. E.g., this will be tell me what content to bring in to the website, where the primer flows into this, and if any new assets, tutorials, etc. need to be included and where.

**Comment by minsiwang04** [comment]
@RaffiSapire : Thanks for your feedback. I updated the proposal base on your comments (on/off ghb) , let me know of any needed additions
