### ISSUE TITLE
TranscoderDAO Governance Experiment

### ISSUE THREAD

**Issue by chrishobcroft** [Livepeer-Community-Node/Grant-Program#21]
### Proposal

To create an Aragon DAO controlled by the 25 Active Transcoders in Livepeer's Protocol, and grant ±3000 LPT from the Decentralised Community Node for the DAO to govern.

Each Transcoder will receive a voting weight proportional to the total stake delegated to them at a given point in time.

Anyone in the world will be free to make proposals for how the funds are spent, and the Transcoders will vote to determine which proposals are accepted.

### Problem Statement

This project is seeking to help relieve some of the burden which currently sits on the shoulders of a set of talented, but scarce, human resources in Livepeer Core. This burden is from the current requirement to run a manual / non-autonomous process to allocate funds generated by the Decentralized Community Node.

This burden creates a bottleneck in terms of funding projects which could help the broader ecosystem. Furthermore, it is placing the responsibility in deciding _how_ these funds are spent, in the hands of these central resources, who cannot possibly be expected to possess all the wisdom which exists in the community. It also risks the inevitable lack of transparency and openness, common to many human-centric processes, which risks giving the impression to the outside world that Livepeer is a closed ecosystem. This is at a time when we are seeing far-reaching experiments building mechanisms to distribute such responsibility to participants in a number of ecosystems.

Livepeer Core are working very hard to deliver Streamflow. This is the community's offer to help lighten the load by "autonomising" part of their workload, and taking some exploratory steps towards further distributing governance of Livepeer.

### Proposed Solution

This project seeks to crowdsource wisdom from existing Transcoder Community in the Livepeer ecosystem by creating a decentralised, autonomous and fully transparent mechanism to allocate a small portion of funds to whatever the Transcoder Community sees fit, as a testbed to experiment with distributing the governance of these funds.

This project can be broken down into the following phases, with incremental funding for each phase.

#### Phase 1 - funding required 0.1 ETH

To create a basic democracy project called `TranscoderDAO` on Aragon, with 100 non-transferable voting tokens (Transcoder DAO Tokens - TDT).

To distribute these TDT proportionally to the addresses of each Livepeer Transcoder, based on the amount of stake delegated to them as of the start of round 1426.

The DAO would require >50% (strict) support for any proposal to pass, and >50% (strict) minimum quorum, and a vote duration of 7 days.

#### Phase 2 - funding required 3000 LPT (or more, or less - as you like)

`unbond`, `withdraw` and `transfer` ±3000 LPT from the Decentralized Community Node to the Aragon DAO.

#### Phase 3 - zero funding required.

Open a post in the Livepeer Forum, to raise awareness of this distributed governance initiative, and to invite proposals (via the Aragon platform), for what to do with these funds.

#### Specific Deliverables

- Phase 1
  - Creation of the TranscoderDAO on Aragon Mainnet
  - Minting of a fixed number of voting tokens, and allocating them to Transcoder's addresses

- Phase 2
  - A signal that the Livepeer Core is distributing governance over centralised decisions

- Phase 3
  - A post in Livepeer Forum providing a link to the DAO, and explanation of how to propose votes (copy to be approved by Livepeer Core)
  - Messages to all known Transcoders, to explain how to participate in the voting process (copy to be approved by Livepeer Core)

#### Specific deliverables in running this experiment

- 2x per week, to publish the content submitted with any votes proposed, on the original post in Livepeer Forum

### Estimated Hours / Costs

- Phase 1
   - **2 hours** to set up the DAO and distribute the voting tokens
   - Cost for this will be recovered via proposing a vote in the DAO
   - **0.1 ETH**, payable in advance, to pay the gas for transactions to create the DAO

- Phase 2
   - **30 minutes** total to `unbond`, `withdraw` and `transfer` LPT to the DAO
   - Elapsed time will be the unbonding period (currently 7 rounds)

- Phase 3
   - **2-6 hours** (dependent on the extent of the feedback on the copy)
   - Cost for this will be recovered via proposing a vote in the DAO

- Ongoing
   - **1 hour per week** to communicate information about the votes on the Livepeer Forum
   - Cost for this will be recovered via proposing votes in the DAO

**Recipe for doing this**

- Go to [Aragon's Mainnet Web User Interface](https://mainnet.aragon.org/#/).
![image](https://user-images.githubusercontent.com/2212651/61892299-c409fa00-af0b-11e9-9f90-42162cccb347.png)

- Select "Token Project with Democracy"
![image](https://user-images.githubusercontent.com/2212651/61891876-eea78300-af0a-11e9-879e-6a48c9e4d9b2.png)

- Give the DAO a name - "transcoderdao.aragonid.eth"
![image](https://user-images.githubusercontent.com/2212651/61891955-1860aa00-af0b-11e9-8677-4ed5f763f2fc.png)

- Create the voting token
![image](https://user-images.githubusercontent.com/2212651/61892044-41813a80-af0b-11e9-96ca-3258354c398e.png)

- Select the DAO's parameters
![image](https://user-images.githubusercontent.com/2212651/61891839-de8fa380-af0a-11e9-96c1-7e3cdbd6488a.png)

After this, the creator of the DAO will need to do the math to calculate how many voting tokens should be allocated to each Transcoder, and to make those allocations.

**Comment by ericxtang** [comment]
A Livepeer transcoderDAO is a great idea!  

It would be great see some proof in the viability and the mechanics of this DAO before committing significant funds to it.  For example, the creation of a test DAO, a test proposal that includes a small amount of LPT, and a test voting procedure that includes 5 to 10 transcoders in the current set.

**Comment by chrishobcroft** [comment]
Thanks @ericxtang :+1: :100: 

That's a great idea, let's not commit significant funds to it until we can see it in action.

Perhaps let's still seek to engage all 25 Active Transcoders from the outset though, instead of limiting this to a select few? And let's also not over-engineer what is intended to be an experiment in how to reduce overhead :)

I would therefore propose to:

- Create the real DAO on mainnet
  - If it's real money, it's more credible
  - Testnet DAOs tend to lack a real feel
  - It's < 0.1 ETH to pay gas to set up
- Allocate voting weight to 25 Transcoders based on Delegated Stake
  - Let's be inclusive, not exclusive?
- Provide 300 LPT from the Decentralized Community Node
  - Let's make this a small but still meaningful amount
  - If it's too small (like 10 LPT), it won't be enough to gain any real interest
- Create a "Governance" category in forum.livepeer.org (needs admin to execute)
  - Create a post in this category which explains what's happening and how to participate
  - Perhaps borrow some inspiration from [Aragon's Community Funding DAO process](https://forum.aragon.org/t/how-to-make-proposals-to-the-community-funding-dao/697) (thank you @john-light)
- Await the first proposals from the Livepeer community (or from the Ethereum community)
  - Multiple concurrent proposals are of course possible
  - There is no limit to the creativity!
  - I personally can't wait to see what they propose!
- Observe how many of Transcoders participate in the vote:
  - They will have 7 days to vote once a proposal is made
  - Some proposals might not reach the required quorum (50%) to pass
  - Maybe not all the votes will be able to pass given the budget
- When all funds have been allocated, grant 2700 LPT from the Decentralized Community Node
  - Without this, it potentially lacks credibility as an experiment.
  - These funds will still be fully under the control of Livepeer Transcoders

If you agree, just deposit 0.1 ETH into [0x9BA4C82Bad962c35D94F598F40f784475dFF510A](https://etherscan.io/address/0x9BA4C82Bad962c35D94F598F40f784475dFF510A) and the rest will follow.

**Comment by chrishobcroft** [comment]
It's also worth noting that [Aragon](https://aragon.org/) run their entire organisation using their own DAO system, with votes based on [Aragon Network Token (ANT)](https://coinmarketcap.com/currencies/aragon/).

For example - the [annual budget of 4,000,000 DAI + 1,675,000 ANT to fund their Core Team](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-5.md) ([Aragon One](https://aragon.one/)) had to pass a vote of ANT holders

Can you imagine Livepeer Core Team's annual budget, plus LPT vesting contracts needing pass a vote of LPT holders?

They also require votes to be passed to fund other distributed autonomous teams building on and in their ecosystem, e.g.

- [450,000 DAI + 125,000 ANT](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-34.md) to fund [Aragon Black](https://www.aragon.black/) for H2 of 2019
- [390,000 DAI for 26 weeks of runway for 6 full time personnel](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-19.md) of [Autark](https://www.autark.xyz/), 
- [500,000 DAI and 200,000 ANT](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-17.md) to fund their [Nest Grant Programme](https://github.com/aragon/nest/))
- [CHF820,000 in DAI + 300,000 ANT for Aragon Association in 2019](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-11.md)
- [12,500 DAI every quarter **without expiration**](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-10.md) for their [Community Funding DAO](https://mainnet.aragon.org/#/agp10/).

Here are details of [Aragon Network Vote #1 from January 2019](https://blog.aragon.org/final-results-from-aragon-network-vote-1/) and [Aragon Network Vote #2 from April 2019](https://blog.aragon.org/final-results-from-aragon-network-vote-2/) and they are [**currently holding** Aragon Network Vote #3](https://blog.aragon.org/final-details-for-aragon-network-vote-3/).

What do you think Livepeer can learn from Aragon about permissionless and transparent governance and creating an ecosystem which promotes open innovation?

**Comment by nelsorya** [comment]
Hey @chrishobcroft, really interesting idea, it could be a really great way to experiment with decentralised governance of community funding. I think it could be very helpful for projects or developers building out tooling for Livepeer and community-driven initiatives. 

If they wanted to, I guess transcoders could allocate a % of their inflation rewards to go to the transcoder DAO over time. Would the LPT in the DAO be staked? I think it's important that it is otherwise it would be diluted over time. I agree that it would be important to start with a small amount of funds which could be scaled over time if it gains traction.

**Comment by RaffiSapire** [comment]
Chris, I think a DAO would be a really interesting experiment and am looking forward to seeing you or anyone else try it. In terms of what can we learn, I'm not sure yet, as I have not seen much traction of them outside of governance-based protocols, but hopefully you or someone else can show us! A DAO can succeed and create amazing outputs, and so can the community node, which has done [an extraordinary amount of work](https://forum.livepeer.org/t/transcoder-campaign-decentralized-community-node/203/12?u=rsap) and doubled the amount its granting per month over the past year from 2000 LPT to over 4000. Success for how community participation occurs is not binary, there is no one right and one wrong. 

I think more methods of funding for projects would be great to see, but it does not makes sense for the community node to fund this grant proposal. Here's why:

1. At this time, funding this open-ended and unproven proposal can introduce regulatory risks that Livepeer as a project cannot take on at the moment (imagine the DAO voted to fund a illegal soccer streaming app, and the funds comes from the community node largely operated by employees of Livepeer inc).

2. The community node is a pool of token that can fund development and projects directly - not just deposit token into another community experiment for allocating token. Furthermore, the node's strategy is to manage these allocations really tightly, based on defined objectives, success criteria, and demonstrated progress. This DAO is an exciting idea that the community will likely get behind, but it's another experiment in fund allocation, and the protocol already has a built in mechanism for other such attempts - inflation funding. There's nothing stopping this project from existing, as it only takes .1 ETH to create the DAO, and it looks like that has already been provided to the address shared in the issue. From that point, inflation funding into a node would be one way for community members who want to participate in a funds allocation experiment to contribute into the DAO pool. Another way would be donations.

It is great time to see more community led initiatives, and I think people would be interested in staking towards or participating as tokenholders in other initiatives. Some feedback for you if you continue this project independently - Maybe start collecting proposals for what to vote on from the community. Then you need to fund your first project, maybe as little as 10 LPT, as Eric suggested? From a process perspective, you'll need people to submit ideas, to get people to go through the action of voting, measure success and share back the outcome. The proposal here is very vague and its not clear what execution looks like. There is no clear process, nothing that is being built since Aragon has built the UI, and its unclear what outcomes would actually be realized. For the community to help vote, as it stands, it would be hard at least for me to know exactly what it is for.

While this isn't a project the community node will fund, I think if you're able to hone in on what you want to fund, and start small, you'll be able to get traction in the community.
